### ISSUE TITLE
Incompatible with WebStorm EAP 2019.3

### ISSUE THREAD

**Issue by ricardomalias** [anstarovoyt/intellij-riot.js#10]
I am receiving a message talking about incompatible version of this plugin.

https://ibb.co/yRmc9S4

There are something that I can do to solve this ?

Ps: I did try to import your project, but I have never done Intellij plugins and don't know what to do about this.

**Comment by anstarovoyt** [comment]
Hi. I will check, thanks

**Comment by anstarovoyt** [comment]
@ricardomalias I have uploaded the new version with 2019.3 compatibility

**Comment by ricardomalias** [comment]
@anstarovoyt  wow ! You really did it ? Thank you so much, normally we haven't get too much support on riot.js stuffs.

**Comment by anstarovoyt** [comment]
@ricardomalias it is https://plugins.jetbrains.com/plugin/12748-riot-js/update/69235 
Please let me know if you have other issues or suggestions.
