### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by lxndrdagreat** [anstarovoyt/intellij-riot.js#11]
First and most importantly, thank you for this plugin!

I was wondering how possible it would be to TypeScript support for Riot 4, or at least in some way make WebStorm chill out about it.

TypeScript can be used as a pre-processor by registering it with the Riot compiler and then marking up the script block like this: `<script type="ts">`.

**Comment by anstarovoyt** [comment]
I will take a look. Unfortunately 'honest' typescript support (using ts service) is very difficult thing for custom file types but at least internal WS annotator should work.

**Comment by anstarovoyt** [comment]
@lxndrdagreat I have added base typescript support in 1.0.8. Please give it a try and share your thoughts.

**Comment by lxndrdagreat** [comment]
I've only had time to look at it briefly, but it looks like it is working great! In any case, WS isn't freaking out about everything and autocomplete seems to be working.
