### ISSUE TITLE
Sass support in style tag

### ISSUE THREAD

**Issue by lxndrdagreat** [anstarovoyt/intellij-riot.js#12]
This is in a similar vein to the TypeScript issue I reported (thanks for fixing that, it's been a huge help!). Would it be possible to do something similar when using Sass inside the Riot tag? You can use Sass via Riot's pre-processor hooks, and then marking up your template with something like `<style type="sass">` or `<style type="scss">`.

Would this be possible? It's yet another case of WS just flipping out about things like this:

```
  <style type="sass">
    :host {
      display: block;
      height: 100vh;
      box-sizing: border-box;
      margin: 0;
      padding: 0;

      & * {
        box-sizing: border-box;
        }
    }
  </style>
```

**Comment by anstarovoyt** [comment]
@lxndrdagreat Hi. I thought that it works. I will take a look, thanks.

**Comment by anstarovoyt** [comment]
@lxndrdagreat are you sure that the code fragment is sass? :)

**Comment by anstarovoyt** [comment]
fixed

**Comment by anstarovoyt** [comment]
@lxndrdagreat please check the version 1.0.9

**Comment by lxndrdagreat** [comment]
@anstarovoyt that looks great, thank you!
