### ISSUE TITLE
Typescript function overload issues

### ISSUE THREAD

**Issue by GianlucaGuarini** [anstarovoyt/intellij-riot.js#19]
It seems that the Intellij Typescript compiler doesn't work properly in Riot.js files, the `withTypes` function overload confuses the IDE.
Moving [this code](https://github.com/riot/examples/blob/5e8fa021a9074f87a597906ba06d948d5766e313/typescript/app/random/random.riot#L24-L45) in a `.ts` file doesn't seem to generate the same issues.

Notice that the above example passes also through the webpack ts loader without issues. 

I am not sure it's a Plugin issue though, can we inform intellij about the problem?

Thank you

**Comment by GianlucaGuarini** [comment]
I have created https://youtrack.jetbrains.com/issue/WEB-52141 to track the problem on the intellij issues tracker

**Comment by anstarovoyt** [comment]
Hi! Thank you, it is a bug in the embedded ts engine of WebStorm
