### ISSUE TITLE
Navigation of basic HTML

### ISSUE THREAD

**Issue by russellmacshane** [anstarovoyt/intellij-riot.js#5]
Hi, thanks for your Webstorm Riot plugin!

This might be more of a question than an actual issue, sorry if it's in the wrong spot.

I'm using Riot 3 and navigation between components works quite well, the issue I'm seeing is that I lose basic HTML and CSS navigation. Do you know of a way that I can make sure both work correctly?

**Comment by anstarovoyt** [comment]
@russellmacshane hi. What do you mean? Could please share an example?

**Comment by russellmacshane** [comment]
<img width="839" alt="Screen Shot 2019-08-02 at 6 37 41 AM" src="https://user-images.githubusercontent.com/8356559/62368653-d5966780-b4f2-11e9-8fa7-96d53305c6a4.png">

This screenshot is without the Riot plugin. Notice that I'm able to click into the section-wrap css property correctly.

<img width="814" alt="Screen Shot 2019-08-02 at 6 54 58 AM" src="https://user-images.githubusercontent.com/8356559/62368654-d5966780-b4f2-11e9-8998-2ca5f895f0cc.png">

This screenshot is with the Riot plugin. Notice that all the Riot syntax is highlighted correctly and that I can click into those particular functions. But, the section-wrap css property does NOT allow me to click into it.

So, my question, is there a way to set this up so that I can click into both Riot properties and HTML/CSS properties at the same time?

**Comment by anstarovoyt** [comment]
@russellmacshane I will take a look this week

**Comment by anstarovoyt** [comment]
@russellmacshane I have resolved the problem. Please try the 1.0.4 version. If you have any other issues please let me know
