### ISSUE TITLE
Syntax highlighting and other features do not work in Webstorm

### ISSUE THREAD

**Issue by olavblj** [anstarovoyt/intellij-riot.js#9]
All text remains white, and none of the features work in Webstorm. It works beautifully in IntelliJ though.

**Comment by olavblj** [comment]
This can be closed. Seems like having the `*.tag` pattern set to mean a HTML file was what caused the problem. This is easily fixed by going into Settings -> Editor -> File Types, selecting Riot Framework, and readding `*.tag` there.

**Comment by anstarovoyt** [comment]
@olavblj I will try to add a notification for users that they need to update the associations

**Comment by anstarovoyt** [comment]
@olavblj added auto updating for file types *.riot and *.tag -> "Riot Framework" if the files already have association with "HTML".
